services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    environment:
      db1_name: ${db1_name}
      db1_user: ${db1_user}
      db1_pwd: ${db1_pwd}
      db1_root_pwd: ${db1_root_pwd}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception

volumes:
  wordpress_data:
      driver: local
      driver_opts:
          type: 'none' 
          device: '/home/asaber/data/wordpress' 
          o: 'bind'
  db_data:
      driver: local
      driver_opts:
          type: 'none'
          o: 'bind'
          device: '/home/asaber/data/mariadb'


networks:
  inception:
    name: inception